version = 0.1
[default.deploy.parameters]
stack_name = "kandidat2006-sam-app"
resolve_s3 = true
s3_prefix = "kandidat2006-sam-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
