on:
  push:
    branches-ignore:
      - main
jobs:
 build-deploy:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: aws-actions/setup-sam@v1
    - run: sam build --use-container
      working-directory: kjell