name: Build image
on:
  push:
    branches-ignore: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t ppe . 
         
          